# Generated by Django 5.0.6 on 2025-09-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_create_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="assigned_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Region/Location this buyer is responsible for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.location",
            ),
        ),
    ]
