# Generated by Django 5.0.6 on 2025-09-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_buyer_assigned_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this main category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Main Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["category__name", "sub_category__name", "name"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Primary category (Fresh Fruit/Fresh Veg)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="main_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Main category classification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.maincategory",
            ),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this sub category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Parent category (Fresh Fruit/Fresh Veg)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="core.productcategory",
                    ),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        help_text="Main category classification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="core.maincategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sub Categories",
                "ordering": ["category__name", "name"],
                "unique_together": {("name", "category")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific sub category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.subcategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("name", "sub_category")},
        ),
    ]
